services:
  postgres:
    image: postgres:latest
    container_name: solarwatch-postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${Database__Name:-solarwatch}
      POSTGRES_USER: ${Database__Username:-john}
      POSTGRES_PASSWORD: ${Database__Password:-123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${Database__Username:-john} -d ${Database__Name:-solarwatch}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    #image: ghcr.io/veggissss/solarwatch/backend:master
    build:
      context: ./backend
      dockerfile: ./SolarWatch/Dockerfile
    container_name: solarwatch-backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    #image: ghcr.io/veggissss/solarwatch/frontend:master
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: solarwatch-frontend
    ports:
      - "4770:4770"
    env_file: .env
    depends_on:
      - api

volumes:
  postgres_data:
